# Generated by Django 4.2.8 on 2024-12-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_remove_income_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
