# Generated by Django 4.2.8 on 2024-12-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_income_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
    ]
