# Generated by Django 4.2.8 on 2024-12-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_alter_income_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
