# Generated by Django 4.2.8 on 2024-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0012_income_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='goal',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='goal_title',
            field=models.CharField(default=None, max_length=75, null=True),
        ),
    ]
