# Generated by Django 4.2.8 on 2024-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0013_income_goal_income_goal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='goal',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
