# Generated by Django 4.2.8 on 2023-12-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='name',
        ),
        migrations.AddField(
            model_name='spending',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
