# Generated by Django 4.2.8 on 2023-12-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_remove_spending_name_spending_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(choices=[('Супермаркеты', 'Супермаркеты'), ('Коммунальные платежи, связь, интернет', 'Коммунальные платежи, связь, интернет'), ('Погашение кредитов', 'Погашение кредитов'), ('Отдых и развлечения', 'Отдых и развлечения'), ('Здоровье и красота', 'Здоровье и красота'), ('Транспорт', 'Транспорт'), ('Прочее', 'Прочее')], default=None, max_length=75),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
