# Generated by Django 4.2.8 on 2023-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0003_alter_spending_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(default=None, max_length=75),
        ),
        migrations.AlterField(
            model_name='spending',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
