# Generated by Django 4.2.8 on 2023-12-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0004_alter_spending_category_alter_spending_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
