# Generated by Django 4.2.8 on 2024-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0007_alter_spending_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='account',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
