# Generated by Django 4.2.8 on 2024-12-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0009_alter_spending_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='account',
            field=models.CharField(default=1, max_length=75),
        ),
    ]
