# Generated by Django 4.2.8 on 2024-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0010_alter_spending_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
