# Generated by Django 4.2.8 on 2024-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0011_spending_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
